apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: user-jvw4x
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-capetown-capetown-bot
  name: capetown-bot
  namespace: capetown
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-capetown-capetown-bot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-capetown-capetown-bot
    spec:
      containers:
      - env:
        - name: BOT_TOKEN
          value: 818252217:AAGaq_H1EWw-XvkxbD1w4k6qijYQWMBiYLI
        - name: DB
          value: database
        - name: DOMAIN_NAME
          value: https://capetown.buttonwallet.com
        - name: INFURA_TOKEN
          value: 1u84gV2YFYHHTTnh8uVl
        - name: LOGIN
          value: admin
        - name: NGROK
          value: https://capetown.buttonwallet.com
        - name: PASSWORD
          value: xEUxN@HVY^AVQWNP
        - name: REDIS_HOST
          value: 10.42.2.43
        - name: URL
          value: 35.204.8.185:31001
        image: krboktv/capetown:bot
        imagePullPolicy: Always
        name: capetown-bot
        ports:
        - containerPort: 8080
          name: 8080tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dc-mt9bl
      - name: docker-neojt
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30